### ISSUE TITLE
Stable release schedule not met -- any update?

### ISSUE THREAD

**Issue by PathosEthosLogos** [twbs/release#18]
>v5.0.0 in February 2021 (stable release)

Under `readme.md`, v5 stable was supposed to be released last month. Just wondering if there's an update or any ETA on this?

**Comment by muralikrishh** [comment]
When can we expect Bootstrap-5 Stable version and Is there any update on stable release date ?

**Comment by yecril71pl** [comment]
The [Upcoming release schedule](https://github.com/twbs/release#upcoming-release-schedule) is obsolete.
