### ISSUE TITLE
Update the EOL date on this .json  page

### ISSUE THREAD

**Issue by babatundeko** [twbs/release#7]
Hi @bardiharborow,

From my previous issue ticket - https://github.com/twbs/bootstrap/issues/29184. I found another page about EOL for 4.x. Can you update on this page as well?

URL: https://github.com/twbs/release/blob/master/schedule.json

Second question, shouldn't each Bootstrap 'family' version (4.x, 5.x, 6.x, etc.) have at least three year life span before EOL? 

Thanks,
Kazeem

**Comment by f-camera** [comment]
Could you please share some updates on the timeline?
E.g. Has 5.x timeline changed? Has the 4.x LTS concept changed?

Thanks.

**Comment by XhmikosR** [comment]
We removed the JSON file due to lack of automation. Any help bringing it back with automation is welcome!
